### ISSUE TITLE
Request for additions to Character class

### ISSUE THREAD

**Issue by ArielHorwitz** [ArielHorwitz/alpha#4]
Character constructor (def __init__) should have an optional parameter for a list of item objects. List of items from this parameter adds those items to the character's backpack when created.

Methods to add:
get/set_occupation(str) - simply a method to get and set a string for local variable.
get/set_modelID(int) - simply a method to get and set an integer for local variable.

**Comment by imcrazeegamer** [comment]
Character Should also have a get/set for location(x,y) and for model ID (int)

_**{I need this stuff to continue developing the GUI }**_

P.S ->> If you guys disagree tell me and tell me how to put it in a subclass instead.

**Comment by ArielHorwitz** [comment]
I agree model ID should exist, I added it to the original post.

Regarding a coordinate, I'm not sure yet how relevant this will be any time soon. Remember that we don't know yet how bad the latency will be to start with, so trying to play on an actual map with locations for each character may not work yet. When I make networking possible we can start testing out latency.

**Comment by imcrazeegamer** [comment]
ok but i can use locations for temp single player version (for testing character intercation (a little a.i bot)) 
(for until you get around to doing the networking magic and for offline testing)

**Comment by ArielHorwitz** [comment]
Yeah that sounds good. You can use your own local variables until we actually implement location in the actual multiplayer.

**Comment by orrdidi** [comment]
Enjoy <3 #7

**Comment by ArielHorwitz** [comment]
@imcrazeegamer See merged pull request #7. If that's good for you I'll close this issue.
